"""Add recurrence_group_id to expenses and incomes

Revision ID: 19cce9d564ba
Revises: cf393d2bdae3
Create Date: 2025-10-06 10:23:25.778692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cce9d564ba'
down_revision = 'cf393d2bdae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_group_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_group_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_column('recurrence_group_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('recurrence_group_id')
    # ### end Alembic commands ###
