"""Migrate

Revision ID: 2262ef09b3cd
Revises: f419e6f99af8
Create Date: 2025-06-08 14:50:40.596354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2262ef09b3cd'
down_revision = 'f419e6f99af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_configuration_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('monthly_target', sa.Float(), nullable=True),
    sa.Column('monthly_actual', sa.Float(), nullable=True),
    sa.Column('cumulative_target', sa.Float(), nullable=True),
    sa.Column('cumulative_actual', sa.Float(), nullable=True),
    sa.Column('is_on_track', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_configuration_id'], ['alert_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_history_alert_configuration_id'), ['alert_configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_history_calculation_date'), ['calculation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('goal_asset_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('goal_target_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_target_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_target_timeframe_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goal_savings_monthly_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_debt_ceiling_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('goal_alert_day_of_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goal_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.drop_column('goal_name')
        batch_op.drop_column('goal_alert_day_of_month')
        batch_op.drop_column('goal_start_date')
        batch_op.drop_column('goal_debt_ceiling_percentage')
        batch_op.drop_column('goal_savings_monthly_amount')
        batch_op.drop_column('goal_target_timeframe_months')
        batch_op.drop_column('goal_target_amount')
        batch_op.drop_column('goal_target_percentage')
        batch_op.drop_column('goal_asset_type')
        batch_op.drop_column('goal_type')

    with op.batch_alter_table('goal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_goal_history_calculation_date'))
        batch_op.drop_index(batch_op.f('ix_goal_history_alert_configuration_id'))

    op.drop_table('goal_history')
    # ### end Alembic commands ###
