"""Add watchlist and watchlist_config tables

Revision ID: 400456190969
Revises: b0644c0e54a7
Create Date: 2026-01-05 16:19:24.705003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400456190969'
down_revision = 'b0644c0e54a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('next_earnings_date', sa.Date(), nullable=True),
    sa.Column('per_ntm', sa.Float(), nullable=True),
    sa.Column('ntm_dividend_yield', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('cagr_revenue_yoy', sa.Float(), nullable=True),
    sa.Column('operativa_indicator', sa.String(length=10), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('cantidad_aumentar_reducir', sa.Float(), nullable=True),
    sa.Column('rentabilidad_5yr', sa.Float(), nullable=True),
    sa.Column('rentabilidad_anual', sa.Float(), nullable=True),
    sa.Column('valoracion_12m', sa.Float(), nullable=True),
    sa.Column('target_price_5yr', sa.Float(), nullable=True),
    sa.Column('precio_actual', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='unique_user_asset_watchlist')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_user_id'), ['user_id'], unique=False)

    op.create_table('watchlist_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_weight_threshold', sa.Float(), nullable=False),
    sa.Column('tier_ranges', sa.Text(), nullable=True),
    sa.Column('tier_amounts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_config_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_config_user_id'))

    op.drop_table('watchlist_config')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_asset_id'))

    op.drop_table('watchlist')
    # ### end Alembic commands ###
