"""add_mic_and_yahoo_suffix_to_assets

Revision ID: 46336b14ad72
Revises: 75da8a370277
Create Date: 2025-10-17 21:28:05.899797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46336b14ad72'
down_revision = '75da8a370277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mic', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('yahoo_suffix', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('yahoo_suffix')
        batch_op.drop_column('mic')

    # ### end Alembic commands ###
