"""add asset registry global table

Revision ID: 4f1f89c92550
Revises: 46336b14ad72
Create Date: 2025-10-19 23:09:30.289245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1f89c92550'
down_revision = '46336b14ad72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('mic', sa.String(length=4), nullable=True),
    sa.Column('degiro_exchange', sa.String(length=10), nullable=True),
    sa.Column('ibkr_exchange', sa.String(length=10), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('yahoo_suffix', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_enriched', sa.Boolean(), nullable=True),
    sa.Column('enrichment_source', sa.String(length=20), nullable=True),
    sa.Column('enrichment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_registry_is_enriched'), ['is_enriched'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_registry_isin'), ['isin'], unique=True)
        batch_op.create_index(batch_op.f('ix_asset_registry_mic'), ['mic'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_registry_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_registry_symbol'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_mic'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_isin'))
        batch_op.drop_index(batch_op.f('ix_asset_registry_is_enriched'))

    op.drop_table('asset_registry')
    # ### end Alembic commands ###
