"""add_color_thresholds_to_watchlist_config

Revision ID: 687340f52345
Revises: 400456190969
Create Date: 2026-01-09 11:20:16.790359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687340f52345'
down_revision = '400456190969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_thresholds', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_config', schema=None) as batch_op:
        batch_op.drop_column('color_thresholds')

    # ### end Alembic commands ###
