"""make asset symbol nullable for degiro

Revision ID: 75da8a370277
Revises: cf481da62623
Create Date: 2025-10-15 22:23:48.962663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75da8a370277'
down_revision = 'cf481da62623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
