"""Add historical price tables for metals and crypto

Revision ID: 7887e2d7cbdc
Revises: bd8e7b703425
Create Date: 2025-06-03 08:29:21.913721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7887e2d7cbdc'
down_revision = 'bd8e7b703425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_crypto_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crypto_symbol', 'date', name='uq_crypto_date')
    )
    op.create_table('historical_metal_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_symbol', 'date', name='uq_metal_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_metal_price')
    op.drop_table('historical_crypto_price')
    # ### end Alembic commands ###
