"""Descripción del cambio: Vista Administrador

Revision ID: 85208f12ea51
Revises: 
Create Date: 2025-05-13 11:11:28.408632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85208f12ea51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())) # CAMBIO AQUÍ
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.true())) # CAMBIO AQUÍ
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=False, server_default=sa.text('0'))) # CAMBIO AQUÍ
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())) # CAMBIO AQUÍ
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now())) # Asumiendo que quieres la fecha actual para los existentes, o NULL si es nullable=True en modelo

        # Alembic podría haber generado una alteración de columna para password_hash si detectó cambio a nullable=True
        # Si tu modelo User tiene password_hash como nullable=True:
        batch_op.alter_column('password_hash',
            existing_type=sa.VARCHAR(length=128),
            nullable=True) # Asegúrate que esto coincida con tu modelo

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('login_count')
        batch_op.drop_column('current_login_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
