"""add_report_templates_and_template_title_to_reports

Revision ID: 8aff15417421
Revises: f74ad63e7d1f
Create Date: 2026-02-06 10:35:21.053361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8aff15417421'
down_revision = 'f74ad63e7d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    # Crear report_templates si no existe (migración parcial previa)
    if 'report_templates' not in tables:
        op.create_table('report_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('report_templates', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_report_templates_user_id'), ['user_id'], unique=False)
    elif 'ix_report_templates_user_id' not in [i['name'] for i in inspector.get_indexes('report_templates')]:
        with op.batch_alter_table('report_templates', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_report_templates_user_id'), ['user_id'], unique=False)

    # Añadir template_id y template_title a company_reports si no existen
    cr_cols = [c['name'] for c in inspector.get_columns('company_reports')]
    cr_indexes = [i['name'] for i in inspector.get_indexes('company_reports')]
    cr_fks = [f['name'] for f in inspector.get_foreign_keys('company_reports')]
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        if 'template_id' not in cr_cols:
            batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        if 'template_title' not in cr_cols:
            batch_op.add_column(sa.Column('template_title', sa.String(length=200), nullable=True))
        if 'ix_company_reports_template_id' not in cr_indexes:
            batch_op.create_index(batch_op.f('ix_company_reports_template_id'), ['template_id'], unique=False)
        if 'fk_company_reports_template_id' not in cr_fks:
            batch_op.create_foreign_key('fk_company_reports_template_id', 'report_templates', ['template_id'], ['id'])

    # Migrar ReportSettings -> ReportTemplate (una plantilla "Plantilla por defecto" por usuario)
    conn = op.get_bind()
    rows = conn.execute(text("SELECT id, user_id, description, points FROM report_settings WHERE description IS NOT NULL AND description != ''")).fetchall()
    for row in rows:
        conn.execute(text("""
            INSERT INTO report_templates (user_id, title, description, points, created_at, updated_at)
            VALUES (:uid, 'Plantilla por defecto', :desc, :pts, datetime('now'), datetime('now'))
        """), {'uid': row[1], 'desc': row[2] or '', 'pts': row[3]})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_reports_template_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_company_reports_template_id'))
        batch_op.drop_column('template_title')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_user_id'))

    op.drop_table('report_templates')
    # ### end Alembic commands ###
