"""Add country field to assets and asset_registry

Revision ID: b0644c0e54a7
Revises: c70487882a86
Create Date: 2025-12-11 16:10:40.858080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0644c0e54a7'
down_revision = 'c70487882a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('country')

    with op.batch_alter_table('asset_registry', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
