"""Add MappingRegistry table for editable mappings

Revision ID: ba500a563900
Revises: 4f1f89c92550
Create Date: 2025-10-20 19:38:41.695247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba500a563900'
down_revision = '4f1f89c92550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_type', sa.String(length=30), nullable=False),
    sa.Column('source_key', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_type', 'source_key', name='uq_mapping_type_key')
    )
    with op.batch_alter_table('mapping_registry', schema=None) as batch_op:
        batch_op.create_index('idx_mapping_lookup', ['mapping_type', 'source_key', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapping_registry_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapping_registry_mapping_type'), ['mapping_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapping_registry_source_key'), ['source_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_registry_source_key'))
        batch_op.drop_index(batch_op.f('ix_mapping_registry_mapping_type'))
        batch_op.drop_index(batch_op.f('ix_mapping_registry_is_active'))
        batch_op.drop_index('idx_mapping_lookup')

    op.drop_table('mapping_registry')
    # ### end Alembic commands ###
