"""Añadir sistema de alertas y buzón virtual

Revision ID: bd5768a6e137
Revises: d9bc047809cf
Create Date: 2025-06-07 20:28:29.478322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5768a6e137'
down_revision = 'd9bc047809cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_reason', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('watchlist_item_id', sa.Integer(), nullable=True),
    sa.Column('days_notice', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('last_triggered_for_date', sa.Date(), nullable=True),
    sa.Column('metric_name', sa.String(length=50), nullable=True),
    sa.Column('metric_operator', sa.String(length=10), nullable=True),
    sa.Column('metric_target_value', sa.Float(), nullable=True),
    sa.Column('summary_type', sa.String(length=50), nullable=True),
    sa.Column('summary_frequency', sa.String(length=20), nullable=True),
    sa.Column('summary_one_time_date', sa.Date(), nullable=True),
    sa.Column('last_summary_sent', sa.Date(), nullable=True),
    sa.Column('custom_title', sa.String(length=200), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('custom_frequency_type', sa.String(length=20), nullable=True),
    sa.Column('custom_start_date', sa.Date(), nullable=True),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_custom_triggered', sa.Date(), nullable=True),
    sa.Column('notify_in_app_mailbox', sa.Boolean(), nullable=False),
    sa.Column('notify_by_email', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_item_id'], ['watchlist_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_configuration_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_configuration_watchlist_item_id'), ['watchlist_item_id'], unique=False)

    op.create_table('mailbox_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('related_watchlist_item_id', sa.Integer(), nullable=True),
    sa.Column('related_alert_config_id', sa.Integer(), nullable=True),
    sa.Column('trigger_event_date', sa.Date(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_alert_config_id'], ['alert_configuration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_watchlist_item_id'], ['watchlist_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mailbox_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailbox_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mailbox_message_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_mailbox_message_related_alert_config_id'), ['related_alert_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mailbox_message_related_watchlist_item_id'), ['related_watchlist_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mailbox_message_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailbox_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailbox_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_mailbox_message_related_watchlist_item_id'))
        batch_op.drop_index(batch_op.f('ix_mailbox_message_related_alert_config_id'))
        batch_op.drop_index(batch_op.f('ix_mailbox_message_is_read'))
        batch_op.drop_index(batch_op.f('ix_mailbox_message_created_at'))

    op.drop_table('mailbox_message')
    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_configuration_watchlist_item_id'))
        batch_op.drop_index(batch_op.f('ix_alert_configuration_user_id'))

    op.drop_table('alert_configuration')
    # ### end Alembic commands ###
