"""Add transaction_hash_unique field for duplicate detection

Revision ID: bd8e7b703425
Revises: 7646dc55e408
Create Date: 2025-05-22 17:31:57.042397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8e7b703425'
down_revision = '7646dc55e408'
branch_labels = None
depends_on = None

# In migrations/versions/bd8e7b703425_add_transaction_hash_unique_field_for_.py

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_csv_movements', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('transaction_hash_unique', sa.String(length=64), nullable=True)) # <--- COMMENT OR DELETE THIS LINE
        # batch_op.create_index(batch_op.f('ix_crypto_csv_movements_transaction_hash_unique'), ['transaction_hash_unique'], unique=False) # <--- AND THIS ONE
        pass # Add pass if you comment out all operations in the block

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_csv_movements', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('ix_crypto_csv_movements_transaction_hash_unique')) # <--- COMMENT OR DELETE THIS LINE
        # batch_op.drop_column('transaction_hash_unique') # <--- AND THIS ONE
        pass # Add pass if you comment out all operations in the block
    # ### end Alembic commands ###
