"""add amount_original and currency_original to transactions

Revision ID: cf481da62623
Revises: 6ac891e79188
Create Date: 2025-10-09 01:25:37.314459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf481da62623'
down_revision = '6ac891e79188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_original', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency_original', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('currency_original')
        batch_op.drop_column('amount_original')

    # ### end Alembic commands ###
