"""Add symbol_yf columns to historical price tables

Revision ID: d9bc047809cf
Revises: 7887e2d7cbdc
Create Date: 2025-06-03 09:03:16.586769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bc047809cf'
down_revision = '7887e2d7cbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_crypto_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_symbol_yf', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('uq_crypto_date', type_='unique')
        batch_op.create_unique_constraint('uq_crypto_date_price', ['crypto_symbol_yf', 'date'])
        batch_op.drop_column('crypto_symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_crypto_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_symbol', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('uq_crypto_date_price', type_='unique')
        batch_op.create_unique_constraint('uq_crypto_date', ['crypto_symbol', 'date'])
        batch_op.drop_column('crypto_symbol_yf')

    # ### end Alembic commands ###
