"""add_audio_tts_to_company_reports

Revision ID: e24b416bfe26
Revises: 8aff15417421
Create Date: 2026-02-06 11:25:05.953576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24b416bfe26'
down_revision = '8aff15417421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('audio_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('audio_error_msg', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audio_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.drop_column('audio_completed_at')
        batch_op.drop_column('audio_error_msg')
        batch_op.drop_column('audio_status')
        batch_op.drop_column('audio_path')

    # ### end Alembic commands ###
