"""Añadir sistema de alertas y buzón virtual

Revision ID: f419e6f99af8
Revises: bd5768a6e137
Create Date: 2025-06-07 21:38:47.331999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f419e6f99af8'
down_revision = 'bd5768a6e137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metric_target_text', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_configuration', schema=None) as batch_op:
        batch_op.drop_column('metric_target_text')

    # ### end Alembic commands ###
