"""add report_settings company_reports asset_about_summary for Gemini reports

Revision ID: f74ad63e7d1f
Revises: 687340f52345
Create Date: 2026-02-05 10:52:08.952462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74ad63e7d1f'
down_revision = '687340f52345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_about_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='unique_user_asset_about_summary')
    )
    with op.batch_alter_table('asset_about_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_about_summary_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_about_summary_user_id'), ['user_id'], unique=False)

    op.create_table('company_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('gemini_interaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_reports_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_reports_user_id'), ['user_id'], unique=False)

    op.create_table('report_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_settings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_settings_user_id'))

    op.drop_table('report_settings')
    with op.batch_alter_table('company_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_reports_asset_id'))

    op.drop_table('company_reports')
    with op.batch_alter_table('asset_about_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_about_summary_user_id'))
        batch_op.drop_index(batch_op.f('ix_asset_about_summary_asset_id'))

    op.drop_table('asset_about_summary')
    # ### end Alembic commands ###
